export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_ARTICLE_DETAILS = 'FETCH_ARTICLE_DETAILS';
export const FETCH_ARTICLES_OF_CATEGORY = 'FETCH_ARTICLES_OF_CATEGORY';
export const FETCH_CATEGORY_METADATA = 'FETCH_CATEGORY_METADATA';
